include .env

export MONGO_CONTAINER_NAME
export MONGO_CONTAINER_TAG
export MONGO_CONTAINER_PORT
export MONGO_INITDB_ROOT_USERNAME
export MONGO_INITDB_ROOT_PASSWORD
export MONGO_INITDB_DATABASE

build_mongo_image:
	docker build -t $(MONGO_CONTAINER_TAG) -f Mongo .

run_mongo_container:
	docker run -p $(MONGO_CONTAINER_PORT):27017 --name $(MONGO_CONTAINER_NAME) \
	-e MONGO_INITDB_DATABASE=$(MONGO_INITDB_DATABASE) \
	-e MONGO_INITDB_ROOT_USERNAME=$(MONGO_INITDB_ROOT_USERNAME) \
	-e MONGO_INITDB_ROOT_PASSWORD=$(MONGO_INITDB_ROOT_PASSWORD) \
	$(MONGO_CONTAINER_TAG)

run_detach_mongo_container:
	docker run -d -p $(MONGO_CONTAINER_PORT):27017 --name $(MONGO_CONTAINER_NAME)  \
	-e MONGO_INITDB_ROOT_USERNAME=$(MONGO_INITDB_ROOT_USERNAME) \
	-e MONGO_INITDB_ROOT_PASSWORD=$(MONGO_INITDB_ROOT_PASSWORD) \ $(MONGO_CONTAINER_TAG)

stop_mongo_container:
	docker stop $(MONGO_CONTAINER_NAME)
	
remove_mongo_container:
	docker rm $(MONGO_CONTAINER_NAME)

remove_mongo_image:
	docker rmi $(MONGO_CONTAINER_TAG)